 <html>
<head>
 <title>РЭУ им. Г. В. Плеханова Кемеровский институт</title>
 <meta http-equiv="Content-Type" content="text/html;  charset=windows=1251">
 <META name="Author" content="http://ailus.ru"><meta name="Copyright" content="http://ailus.ru">
 </head>
 
 <body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" rightmargin="0" bottommargin="0" bgcolor="#ffffff">
 <link href="index.css" type="text/css" rel="STYLESHEET">
 
 <table border=1 width=100% height=20%>
 
 <td width=100% height=20% align=center> Лабораторные работы по курсу "Разработка интернет приложений" <br> Студентов группы ПИ-153: Литау Никиты и Новикова Ильи <br> Проверил: к. т. н. доц. Назимов А. С.</td>
 
 </table>
 
 <table border=1 width=100% height=70%>
<td width=30% height=70% align=left>
 
<a href="orderform.php"> Первая лабораторная рaбота </a>
<br><br>
<a href="orderform_2.php"> Вторая лабораторная рaбота </a>
<br><br>
<a href="orderform_3.php"> Третья лабораторная рaбота </a>
<br><br>
<a href="orderform_4.php"> Четвертая лабораторная рaбота </a>
<br><br>
<a href="autoforum_galery.php"> Пятая лабораторная рaбота </a>
<br><br>
<a href="orderform_5.php"> Шестая лабораторная рaбота</a>
<br><br>

</td>
<td width=70% height=70% align=center>